### ISSUE TITLE
improve charts

### ISSUE THREAD

**Issue by gregw** [jetty-project/jetty-load-generator#1]
The charts of results (eg https://jenkins.webtide.net/job/load-testing/job/jetty_load_test_9.4.x/) have the max value dominating the mean, so it is not possible to see any variation in the mean.

Either the max and mean need to be plotted on different scales, or perhaps a log scale would allow better visibility of changes to the mean.

**Comment by olamy** [comment]
@gregw this issue is related to the jenkins plugin and sources are located here https://github.com/olamy/loadgenerator-plugin 
I wonder where to move those sources? https://github.com/webtide ?

**Comment by olamy** [comment]
BTW I agree this max su... :-)

**Comment by olamy** [comment]
project moved to https://github.com/webtide/loadgenerator-plugin
see https://github.com/webtide/loadgenerator-plugin/issues/12

**Comment by olamy** [comment]
fixed.
