### ISSUE TITLE
Add timeout to Resource

### ISSUE THREAD

**Issue by olamy** [jetty-project/jetty-load-generator#15]
per default timeout is 60000. Maybe we could make it configurable at resource level.
@sbordet  WDYT?

**Comment by sbordet** [comment]
what kind of timeout ?

**Comment by olamy** [comment]
the read/response timeout: request.timeout(  ). (I would not fail the load but report the timeout in Resource.Info)
WDYT?
PS: Well we probably the connectTimeout as well but in the LoadGenerator.config level.

**Comment by sbordet** [comment]
I'm not sure about this. We typically send a "resource" timeout, meaning the whole tree. Having a per-request/response timeout is fine, but how does it apply to the whole tree ?

Right now there is no timeout, as far as I can see. Where did you get that 60s value ?

**Comment by olamy** [comment]
Oh correct. I missed the point about Resource can be a whole tree. 
I was thinking about timeout at the uri level. Resource("/foo/beer/blabla").timeout(15, TimeUnit.SECONDS) meaning 15s max for request to "/foo/beer/blabla". (so the default 60s)
But I/users can simply read results and decide if it was a timeout or not.
So closing
