### ISSUE TITLE
Remove usages of RateLimiter

### ISSUE THREAD

**Issue by sbordet** [jetty-project/jetty-load-generator#16]
@olamy, `RateLimiter` blocks and therefore we don't want to use it in this load generator.

I'm not sure why `RateLimiter` is used at all. The load generator runs at the given rate by design, so why you want to limit the rate, that won't be exceeded anyway ?

**Comment by olamy** [comment]
it's optional and not used per default. I was able to generate traffic with less spike as the limit is at a lower level. As I understand the current rate limitation is before request are queued. So in case of a big queue (server took time to answer) suddenly when the server answer dequeuing can be faster that the rate. 
Anyway if you don't like this optional component I don't mind moving it somewhere else.

**Comment by sbordet** [comment]
@olamy this `RateLimiter` limits the request sending. If there is queueing in sending requests, the load generator is not configured properly because it cannot sustain its own load.
Yes, removing it and associated classes.

**Comment by olamy** [comment]
yup it's the goal to limit to a given rate.
Again it's optional and not used per default. And it can really help users.

**Comment by olamy** [comment]
maybe in starter module (out of core part)?

**Comment by sbordet** [comment]
@olamy I don't understand what it is for. We already have a way to specify the rate. Why do we need 2 ways of specifying the rate ?

**Comment by olamy** [comment]
As I can understand we currently "limit" the queueing and not sending.
For any reasons in case of some long response from the target server, the queue size can increase and then suddenly (when server is back) all requests are dequeueing which generate some burst we don't really want. 
Anyway I removed the classes :-)
