### ISSUE TITLE
Link to docs is not working

### ISSUE THREAD

**Issue by ahus1** [jetty-project/jetty-load-generator#421]
This repository lists in its About a URL that leads to a 404

![image](https://github.com/user-attachments/assets/a2138860-2cf5-471b-9fd8-365995c01242)

The URL listed there: 
https://jetty-project.github.io/jetty-load-generator/

Please update it with a working URL

**Comment by sbordet** [comment]
Removed the link, it was never meant to show neither the website nor the documentation.

Thanks!
