### ISSUE TITLE
Expose Resource as a Request attribute

### ISSUE THREAD

**Issue by sbordet** [jetty-project/jetty-load-generator#63]
Would be handy to have access to the `Resource` from a `Request.Listener` via a `Request` attribute.

**Comment by an-hong23** [comment]
Can you also change the jetty-load-generator to use Jetty version 9.4.37.v20210219?   We are upgrading to that version and would like to have dependency on only one version.

**Comment by sbordet** [comment]
@an-hong23 we will soon release 9.4.38 due to a regression, I'll update to that.
