### ISSUE TITLE
JMX flag has no effect

### ISSUE THREAD

**Issue by QAInsights** [jetty-project/jetty-load-generator#66]
I tried below command in Windows with the jmx flag. But I don't see the export in the current dir. Please check.

`java -jar .\jetty-load-generator-starter-1.0.4-uber.jar --scheme https --host example.com --port 443 --resource-rate 1 --iterations 3 --display-stats --jmx true`

**Comment by sbordet** [comment]
"Exporting to JMX" means that the load generator components are exported to the platform `MBeanServer` as MBeans.

I'll clarify the description on the command line usage.

**Comment by QAInsights** [comment]
Thank you. I was thinking from JMeter perspective where I thought the command will export the URL into JMeter test plan.
