### ISSUE TITLE
Threads must wait to be ready

### ISSUE THREAD

**Issue by sbordet** [jetty-project/jetty-load-generator#8]
Performing work in N threads must ensure that the N threads are really all started and ready to perform the work.

Currently, `Runnable` tasks are created and submitted to the `Executor` in a loop, which may cause the first task to run to completion before the second task is even submitted.

The code should use a barrier that waits for all the threads to be ready, and only then release the barrier to make all the threads perform the work.

**Comment by olamy** [comment]
done
